# Generated by Django 5.2.4 on 2025-07-30 19:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('add_to_cart_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Conversion rate from views to purchases (%)')),
                ('engagement_rate', models.FloatField(default=0.0, help_text='Engagement rate (likes + comments + shares) / views (%)')),
                ('performance_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_analytics', to='products.product')),
            ],
            options={
                'db_table': 'stores_product_analytics',
            },
        ),
        migrations.CreateModel(
            name='StoreAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('active_products', models.PositiveIntegerField(default=0)),
                ('out_of_stock_products', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.FloatField(default=0.0, help_text='AI-calculated popularity score (0-100)')),
                ('engagement_score', models.FloatField(default=0.0, help_text='AI-calculated engagement score (0-100)')),
                ('quality_score', models.FloatField(default=0.0, help_text='AI-calculated quality score based on reviews (0-100)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_analytics', to='products.store')),
            ],
            options={
                'db_table': 'stores_analytics',
            },
        ),
        migrations.CreateModel(
            name='ProductViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('view_duration', models.PositiveIntegerField(default=0, help_text='Time spent viewing product in seconds')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_view_logs',
                'indexes': [models.Index(fields=['product', 'viewed_at'], name='product_vie_product_d4df3e_idx'), models.Index(fields=['user', 'viewed_at'], name='product_vie_user_id_ec03cd_idx'), models.Index(fields=['session_id', 'viewed_at'], name='product_vie_session_8cea4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_description', models.TextField()),
                ('business_type', models.CharField(help_text='Type of business (e.g., Electronics, Clothing, etc.)', max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_address', models.TextField()),
                ('business_license', models.CharField(help_text='Business license number', max_length=100)),
                ('tax_id', models.CharField(help_text='Tax identification number', max_length=50)),
                ('business_license_document', models.FileField(blank=True, null=True, upload_to='store_applications/licenses/')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='store_applications/identity/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_applications',
                'indexes': [models.Index(fields=['applicant', 'status'], name='store_appli_applica_f654a3_idx'), models.Index(fields=['status', 'created_at'], name='store_appli_status_e743b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('service_rating', models.PositiveIntegerField(help_text='Customer service rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('delivery_rating', models.PositiveIntegerField(help_text='Delivery experience rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product_quality_rating', models.PositiveIntegerField(help_text='Product quality rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('owner_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_feedback', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='products.store')),
            ],
            options={
                'db_table': 'store_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'rating', 'created_at'], name='store_feedb_store_i_8af615_idx'), models.Index(fields=['customer', 'created_at'], name='store_feedb_custome_8805fc_idx')],
                'unique_together': {('store', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='StoreNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_review', 'New Review'), ('low_stock', 'Low Stock Alert'), ('high_engagement', 'High Engagement'), ('performance_milestone', 'Performance Milestone'), ('system_update', 'System Update')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.store')),
            ],
            options={
                'db_table': 'store_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'is_read', 'created_at'], name='store_notif_store_i_414325_idx'), models.Index(fields=['notification_type', 'created_at'], name='store_notif_notific_5ac78e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='products.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_view_logs',
                'indexes': [models.Index(fields=['store', 'viewed_at'], name='store_view__store_i_cee423_idx'), models.Index(fields=['user', 'viewed_at'], name='store_view__user_id_c3ee54_idx'), models.Index(fields=['session_id', 'viewed_at'], name='store_view__session_e9ac36_idx')],
            },
        ),
    ]
