# Generated by Django 5.2.4 on 2025-08-02 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefeedback',
            name='delivery_rating',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Delivery experience rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='storefeedback',
            name='product_quality_rating',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Product quality rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='storefeedback',
            name='service_rating',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='Customer service rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
